import cx from 'classnames';
import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Noto_Sans } from 'next/font/google';

import ThemeToggle from '@/components/theme-toggle';

import './globals.scss';

const notoSans = Noto_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Open Weather App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={cx(notoSans.className, 'text-sm sm:text-base')}>
        <ThemeProvider attribute='class'>
          <div className='min-h-dvh bg-[url("/bg-light.png")] bg-fixed bg-center pb-4 dark:bg-[url("/bg-dark.png")] md:pb-8'>
            {children}
            <ThemeToggle />
          </div>
        </ThemeProvider>
        <div id='modal' />
      </body>
    </html>
  );
}
